micronaut:
  application:
    name: micronautRedisPlayground

endpoints:
  health:
    enabled: true

redis:
  host: "${REDIS_DEFAULT_HOST:redis-master}"
  port: ${REDIS_DEFAULT_PORT:6379}
  password: "${REDIS_PASSWORD:changeit}"

  servers:
    pub:
      host: "${REDIS_PUB_HOST:redis-master}"
      port: ${REDIS_PUB_PORT:6379}
      password: "${REDIS_PUB_PASSWORD:changeit}"
    sub:
      host: "${REDIS_SUB_HOST:redis-master}"
      port: ${REDIS_SUB_PORT:6379}
      password: "${REDIS_SUB_PASSWORD:changeit}"

netty:
  default:
    allocator:
      max-order: 3
